---
output: html_document
---

```{r}
#### generate bipartite matrix
library(arules)
library(knitr)
library(Matrix)
nItems = 25

set.seed(3)
############ SIMULATE TRANSACTIONS (using Agrawal method) ############
nTrans = 10
# generate random itemsets and give them a probability distribution
patterns <- random.patterns(nItems = nItems, nPats = 5, corr = 0, 
                            lPats = 2, cmean = .5, cvar = 0.1)

data = list()
for (i in 1:nTrans) {
  j = rpois(1,1)+1 # how many itemsets does the transaction contain (add one to avoid empty transactions)
  k = findInterval(runif(j), cumsum(patterns@quality$pWeights)) + 1 # which itemsets #######
  trans1 = c()
    for (q in 1:length(k)) {
      trans1 = c(trans1,patterns@items@itemInfo$labels[which(patterns@items@data[,k[q]]==TRUE)])
    }
  data[[i]] = unique(trans1)
}
data
data <- as(data, "transactions") # coerce to transaction data structure

M = t(array(as.numeric(data@data), dim = c(data@data@Dim[1],data@data@Dim[2])))

```


```{r, echo=FALSE, message=FALSE, warning=FALSE}
# toy dataset
data <- list(
c("a","b","c"),
c("a","b"),
c("a","b","d"),
c("b","e"),
c("b","c","e"),
c("a","d","e"),
c("a","c"),
c("a","b","d"),
c("c","e"),
c("a","b","d","e"),
c("a",'b','e','c')
)
data <- as(data, "transactions")

M = t(array(as.numeric(data@data), dim = c(data@data@Dim[1],data@data@Dim[2])))

```


```{r}
## construct adjacency matrix
k = dim(M)[1] # edges (V1)
n = dim(M)[2] # nodes (V2)

# adjacency matrix
Ma = matrix(0,ncol=n+k, nrow=n+k)
Ma[1:k,(k+1):(k+n)] = M
Ma[(k+1):(k+n),1:k] = t(M)

# transition matrix
Pa = t(Ma/colSums(Ma))
```

```{r}
# algorithm - Exact NF
norm_vec <- function(x) sqrt(sum(x^2)) # calculates the 

exact_NF = function(Ma, c, tol = 1e-6) {
  mat = array(0, dim = c(k,k))
  ua = array(0,dim=c(k+n,1))
  for (i in 1:k) {
    ua[i] = 1
    query = ua
    repeat {
        q = ua 
        ua = (1-c) * Pa %*% q + c * query
        if (abs(norm_vec(ua)-norm_vec(q)) < tol) break
    }
    mat[,i] = ua[1:k]
  }
  return(mat)
}

```




